### ISSUE TITLE
Score should be 16 (10 + 3 + 3)?

### ISSUE THREAD

**Issue by clschnei** [gumballhead/bowling#1]
https://github.com/gumballhead/bowling/blob/0636e174e8e3b6f33197c0270973fbb903bf8ff9/tests/score_test.py#L24

![image](https://user-images.githubusercontent.com/1232625/46164829-036ca900-c25d-11e8-8f17-abe36b236098.png)

**Comment by kirkedev** [comment]
Haha, you're correct of course, but that function is meant to score a frame and its bonus balls (frame 1 in your example), not the running total
